import CustomImage from "@/components/CustomImage";
import FirstPage from "@/components/HomePage/FirstPage";
import SecondPage from "@/components/HomePage/SecondPage";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<FirstPage />
			<SecondPage />
		</>
	);
}
